# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvote',
            name='choice_hash',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='voter_name',
            field=models.CharField(max_length=255),
        ),
    ]
