# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='售价')),
            ],
            options={
                'verbose_name_plural': '设备',
                'verbose_name': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='device.DeviceCategory', verbose_name='上一级类别')),
            ],
            options={
                'verbose_name_plural': '设备分类',
                'ordering': ['order'],
                'verbose_name': '设备分类',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceCategory', verbose_name='分类'),
        ),
    ]
