# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-12 08:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='活动名称')),
                ('description', models.CharField(max_length=50, verbose_name='活动描述')),
                ('video', models.FileField(upload_to=home.models.Activity.activity_path, verbose_name='活动视频')),
                ('thumbnail', models.ImageField(upload_to=home.models.Activity.activity_path, verbose_name='缩略图')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
            ],
            options={
                'verbose_name': '活动',
                'ordering': ['order'],
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='横幅主题')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='图像')),
                ('link', models.URLField(verbose_name='链接')),
                ('position', models.CharField(choices=[('carousel', '首页跑马灯'), ('hotpot', '公开课热门页')], max_length=32, verbose_name='位置')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '横幅',
                'ordering': ['order'],
                'verbose_name_plural': '横幅',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程名')),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(upload_to=home.models.Lesson.dir_path, verbose_name='缩略图')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='价格')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('equipment', models.CharField(blank=True, max_length=100, verbose_name='设备')),
                ('description', models.CharField(max_length=60, verbose_name='描述')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '课程',
                'ordering': ['order'],
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='课程类别')),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('lessons', models.PositiveIntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.LessonCategory')),
            ],
            options={
                'verbose_name': '课程分类',
                'ordering': ['order'],
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程视频名称')),
                ('file', models.FileField(upload_to=home.models.LessonVideo.video_path, verbose_name='视频文件')),
                ('duration', models.DurationField(verbose_name='视频时长')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('thumbnail', models.ImageField(upload_to=home.models.LessonVideo.video_path, verbose_name='缩略图')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lesson', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程视频',
                'ordering': ['order'],
                'verbose_name_plural': '课程视频',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LessonCategory', verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='老师'),
        ),
    ]
