# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order'], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='lessoncategory',
            options={'ordering': ['order'], 'verbose_name': '课程分类', 'verbose_name_plural': '课程分类'},
        ),
        migrations.AlterModelOptions(
            name='lessonvideo',
            options={'ordering': ['order'], 'verbose_name': '课程视频', 'verbose_name_plural': '课程视频'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='lessonvideo',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='顺序'),
        ),
    ]
