# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161111_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=30, verbose_name='课程名'),
        ),
    ]
