# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161112_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
