# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('home', '0003_lessonvideo_mimetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='equipment',
        ),
        migrations.AddField(
            model_name='lesson',
            name='equipment',
            field=models.ManyToManyField(to='device.Device', verbose_name='设备'),
        ),
    ]
