# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161111_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=50, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=64, verbose_name='横幅主题'),
        ),
    ]
