# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 12:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161125_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问题')),
                ('answer', models.CharField(max_length=255, verbose_name='答案')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name_plural': '常见课程问题',
                'verbose_name': '常见课程问题',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='lessonvideo',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='advice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groupSuit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='其他'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='Lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lesson', verbose_name='课程'),
        ),
    ]
