# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161128_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='advice',
            field=models.CharField(blank=True, max_length=255, verbose_name='学习建议'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='groupSuit',
            field=models.CharField(blank=True, max_length=255, verbose_name='适合人群'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, verbose_name='课程简介'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='target',
            field=models.CharField(blank=True, max_length=255, verbose_name='课程目的'),
        ),
    ]
